# Generated by Django 5.2.17 on 2026-08-19 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_dml_insert_category_data_by_fixture_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='import_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.salesfile', verbose_name='売上ファイルID'),
        ),
    ]
