# Generated by Django 5.2.17 on 2026-08-26 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='あらすじ')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='上映時間')),
                ('release_date', models.DateField(verbose_name='公開日')),
                ('rating', models.CharField(choices=[('G', '全年齢'), ('PG12', 'PG12'), ('R15', 'R15'), ('R18', 'R18')], default='G', max_length=10, verbose_name='レーティング')),
            ],
            options={
                'verbose_name': '映画',
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='スクリーン名')),
                ('row_count', models.PositiveIntegerField(verbose_name='座席の行数')),
                ('col_count', models.PositiveIntegerField(verbose_name='座席の列数')),
            ],
            options={
                'verbose_name': 'スクリーン',
                'verbose_name_plural': 'スクリーン一覧',
                'db_table': 'screen',
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='劇場名')),
                ('address', models.CharField(max_length=200, verbose_name='住所')),
            ],
            options={
                'verbose_name': '劇場',
                'db_table': 'theater',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True, verbose_name='予約日時')),
                ('total_price', models.PositiveIntegerField(verbose_name='合計金額')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '仮押さえ'), ('confirmed', '確定'), ('cancelled', 'キャンセル')], default='pending', max_length=20, verbose_name='予約状態')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '予約',
                'db_table': 'reservation',
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('earn', '付与'), ('redeem', '交換使用')], max_length=10)),
                ('amount', models.IntegerField(help_text='earnは正の値、redeemは負の値')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_label', models.CharField(max_length=10, verbose_name='行ラベル')),
                ('seat_number', models.PositiveIntegerField(verbose_name='席番号')),
                ('seat_type', models.CharField(max_length=100, verbose_name='席タイプ')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.screen')),
            ],
            options={
                'verbose_name': '座席',
                'db_table': 'seat',
            },
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='上映開始時間')),
                ('end_time', models.DateTimeField(verbose_name='上映終了時間')),
                ('base_price', models.PositiveIntegerField(verbose_name='基本料金')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.screen')),
            ],
            options={
                'verbose_name': '上映回',
                'db_table': 'showtime',
            },
        ),
        migrations.CreateModel(
            name='ReservationSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='座席価格')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.reservation')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.seat')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.showtime')),
            ],
            options={
                'verbose_name': '予約座席',
                'db_table': 'reservation_seat',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='showtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.showtime'),
        ),
        migrations.AddField(
            model_name='screen',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.theater'),
        ),
        migrations.CreateModel(
            name='UserPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', '現金'), ('point', 'ポイント交換')], max_length=10)),
                ('amount', models.PositiveIntegerField(help_text='現金決済時の金額', verbose_name='決済金額')),
                ('points_used', models.PositiveIntegerField(default=0, help_text='ポイント決済時のみ')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', '仮押さえ'), ('paid', '決済済')], default='pending', max_length=20, verbose_name='決済状態')),
                ('confirmed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='cinema.reservation')),
            ],
            options={
                'verbose_name': '決済',
                'db_table': 'payment',
                'constraints': [models.CheckConstraint(condition=models.Q(('method', 'point'), ('status', 'pending'), _negated=True), name='point_payment_cannot_be_peding')],
            },
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('screen', 'row_label', 'seat_number'), name='unique_seat_per_screen'),
        ),
        migrations.AddConstraint(
            model_name='reservationseat',
            constraint=models.UniqueConstraint(fields=('seat', 'showtime'), name='unique_seat_per_showtime'),
        ),
    ]
