# Generated by Django 5.2.17 on 2026-08-26 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointtransaction',
            options={'verbose_name': 'ポイント履歴'},
        ),
        migrations.AlterModelOptions(
            name='userpoint',
            options={'verbose_name': 'ユーザーポイント'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL, verbose_name='会計確定した職員'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='決済完了日時'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='決済金額'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='決済確定日時'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', '現金'), ('point', 'ポイント交換')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='points_used',
            field=models.PositiveIntegerField(default=0, verbose_name='使用ポイント数'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.reservation'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', '仮確定(未払い)'), ('confirmed', '確定済み'), ('cancelled', 'キャンセル')], default='pending', max_length=20, verbose_name='決済状態'),
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='amount',
            field=models.IntegerField(verbose_name='増減量(付与・返還は正、交換は負)'),
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='type',
            field=models.CharField(choices=[('earn', '付与'), ('redeem', '交換使用'), ('refund', '返還')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='来場確認日時'),
        ),
        migrations.AlterField(
            model_name='userpoint',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='保有ポイント'),
        ),
        migrations.AlterModelTable(
            name='pointtransaction',
            table='point_transaction',
        ),
        migrations.AlterModelTable(
            name='userpoint',
            table='user_point',
        ),
    ]
