# Generated by Django 5.2.17 on 2026-08-27 04:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_pointtransaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='point_payment_cannot_be_peding',
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('method', 'point'), ('status', 'pending'), _negated=True), name='point_payment_cannot_be_pending'),
        ),
    ]
