# Generated by Django 5.2.17 on 2026-09-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_reservation_checkin_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='有効期限'),
        ),
    ]
